IF EXISTS ( SELECT 1
            FROM   sysobjects 
            WHERE  id = object_id(N'[dbo].[GETPATIENTSINFORMATION]') 
                   and OBJECTPROPERTY(id, N'IsProcedure') = 1 )
BEGIN
    DROP PROCEDURE [dbo].[GETPATIENTSINFORMATION]
END
GO

CREATE PROCEDURE [DBO].[GETPATIENTSINFORMATION]
AS
BEGIN
    SELECT PATIENTID,PATIENTDATA FROM PATIENT
END
GO