IF EXISTS ( SELECT 1
            FROM   sysobjects 
            WHERE  id = object_id(N'[dbo].[SAVEPATIENTSINFORMATION]') 
                   and OBJECTPROPERTY(id, N'IsProcedure') = 1 )
BEGIN
    DROP PROCEDURE [dbo].[SAVEPATIENTSINFORMATION]
END
GO
CREATE PROCEDURE [DBO].[SAVEPATIENTSINFORMATION]
(@PATIENTXML)
AS
BEGIN
    INSERT INTO DBO.PATIENT(PATIENTDATA) VALUES(@PATIENTXML)
END