IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'PATIENT' AND TABLE_SCHEMA = 'DBO')
   BEGIN
    DROP TABLE DBO.PATIENT
   END
   GO
   
CREATE TABLE [DBO].[PATIENT](

PATIENTID INT NOT NULL,
PATIENTDATA XML NOT NULL,
PRIMARY KEY CLUSTERED
(
[PATIENTID] ASC
)
)ON [PRIMARY]

GO